env:
  commonjs: true
  es6: true
  node: true
  mocha: true
extends:
  - airbnb-base
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: 'babel-eslint'
parserOptions:
  ecmaVersion: 11
rules: {
  no-underscore-dangle: 0,
  consistent-return: 1,
  camelcase: 0,
  no-unused-vars: 1,
  max-len: 0,
  func-names: 0,
  no-param-reassign: 1,
  no-plusplus: 0,
  array-callback-return: 1,
}
